<?php

/**
 * Todo: 
 * - integration with modules
 *   * (node-) clone
 *   * Webform template
 */

/**
 * Implement hook_menu
 * @return array
 */
function webform_scoring_menu() {
  $items = array();

  $items['node/%webform_menu/webform/scoring-rules'] = array(
    'title' => 'Scoring Rules',
    'page callback' => 'webform_scoring_scoring_rules',
    'page arguments' => array(1, 4, 5),
    'access callback' => 'webform_results_access',
    'access arguments' => array(1),
    'weight' => 6,
    'file' => 'includes/pages/rule.manage.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['node/%webform_menu/webform-results/scores'] = array(
    'title' => 'Scores',
    'page callback' => 'webform_scoring_scores',
    'page arguments' => array(1),
    'access callback' => 'webform_results_access',
    'access arguments' => array(1),
    'weight' => 6,
    'file' => 'includes/pages/score.view.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Calculate the score for the result of a submission
 * @param type $node
 * @param type $data
 * @return boolean|array
 */
function webform_scoring_calculate_score($node, $data) {
  module_load_include('inc', 'webform_scoring', 'includes/pages/rule.manage');
  $score_enabled = _webform_score_enabled($node->nid);
  if ($score_enabled->enabled && _webform_score_has_cid($node, $score_enabled->cid)) {
    $query = db_select('webform_scoring_values_scores_pair', 'a');
    $query->fields('a');
    $query->condition('a.nid', $node->webform['nid'], '=');
    $result = $query->execute()->fetchAll(PDO::FETCH_ASSOC);

    $score_key = array();
    $cid_list = array();
    //$component = array();
    foreach ($result as $item) {
      $pairs = array();
      $score_key[$item['cid']]['cid'] = $item['cid'];
      array_push($cid_list, $item['cid']);
      $lines = explode("\n", trim($item['value_score_pair']));
      foreach ($lines as $com_val) {
        $pair = array();
        $com_val = explode("|", $com_val);
        $pair['value'] = $com_val[0];
        $pair['score'] = $com_val[1];
        array_push($pairs, $pair);
      }
      $score_key[$item['cid']]['pairs'] = $pairs;
    }
    $total_score = 0;
    foreach ($data as $key => $values) {
      if (!is_array($values)) {
        $values = array($values);
      }
      if (in_array($key, $cid_list)) {
        foreach ($score_key[$key]['pairs'] as $vs_pair) {
          // done: cummulative
          if (in_array($vs_pair['value'], $values)){
            $total_score += $vs_pair['score'];
          }
          // todo: average
          // todo: minimum
          // todo: maximum
          // todo: has/has-not value
        }
      }
    }
    return $total_score;
  }

  return FALSE;
}

/**
 * Store a quiz result upon submission presave
 * @param type $node
 * @param type $submission
 */
function webform_scoring_webform_submission_presave($node, &$submission) {
  $total_score = webform_scoring_calculate_score($node, $submission->data);

  if ($total_score !== FALSE) {
    $score_enabled = _webform_score_enabled($node->nid);
    $submission->data[$score_enabled->cid][0] = $total_score;
  }
}
